### ISSUE TITLE
Crashes when loading a game as of TLD v 1.86

### ISSUE THREAD

**Issue by Darth-Taco** [zeobviouslyfakeacc/HungerRevamped#4]
This mod no longer appears to work after the 1.86 update a few days ago.  TLD crashes to desktop when starting a game when this mod is loaded.

**Comment by zeobviouslyfakeacc** [comment]
Yeah, unfortunately. I haven't really been able to track down the issue so far, and I currently don't really have the time to work on TLD mods. You'll probably have to play TLD without HungerRevamped for now. Sorry.

**Comment by zeobviouslyfakeacc** [comment]
... I completely forgot to resolve this bug report.
This issue was fixed in commit fdf9f39c59126ee54075a49b56c790c00c5931b9, and the working version 1.8 of HungerRevamped was released [here](https://github.com/zeobviouslyfakeacc/HungerRevamped/releases/tag/v1.8) in December of 2020.
Sorry about the delay.
